version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
     - 8082:8080
     - 50000:50000
    container_name: jenkins
    volumes:
     - C:/Users/JuanFassio/Desktop/Code/Python-Wallet-API/jenkins_home:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock